---
  name: install apache and php
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: password
  tasks:
    - name: install apache on Ubuntu, Debian
      apt:
        name: 
        - apache2
        - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: install apache on CentOS
      dnf:
        name: 
        - httpd
        - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"